import { AppConfig } from '../types/config';

export function generateConfigFile(config: AppConfig): string {
  return `/**
 * ${config.appName} Configuration
 * 
 * Generated by White-Label App Configurator
 */

module.exports = {
  // App Identity
  appName: '${config.appName}',
  slug: '${config.slug}',
  scheme: '${config.scheme}',
  version: '${config.version}',

  // Assets
  icon: './assets/${config.slug}/icon.png',
  splash: {
    image: './assets/${config.slug}/splash.png',
    resizeMode: 'contain',
    backgroundColor: '${config.brandColors.primary}',
  },

  // iOS Configuration
  ios: {
    bundleIdentifier: '${config.bundleIdentifier}',
    icon: './assets/${config.slug}/icon.png',
  },

  // Android Configuration
  android: {
    package: '${config.androidPackage}',
    adaptiveIcon: {
      foregroundImage: './assets/${config.slug}/adaptive-icon.png',
      backgroundColor: '${config.brandColors.primary}',
    },
  },

  // Web Configuration
  web: {
    favicon: './assets/${config.slug}/favicon.png',
  },

  // Brand Colors
  brandColors: {
    primary: '${config.brandColors.primary}',
    secondary: '${config.brandColors.secondary}',
    accent: '${config.brandColors.accent}',
    background: '${config.brandColors.background}',
    text: '${config.brandColors.text}',
    error: '${config.brandColors.error}',
    success: '${config.brandColors.success}',
  },

  // Typography
  typography: {
    fontFamily: {
      heading: '${config.typography.fontFamily.heading}',
      body: '${config.typography.fontFamily.body}',
      monospace: '${config.typography.fontFamily.monospace}',
    },
    fontSize: {
      xs: ${config.typography.fontSize.xs},
      sm: ${config.typography.fontSize.sm},
      md: ${config.typography.fontSize.md},
      lg: ${config.typography.fontSize.lg},
      xl: ${config.typography.fontSize.xl},
      xxl: ${config.typography.fontSize.xxl},
    },
    fontWeight: {
      normal: '${config.typography.fontWeight.normal}',
      medium: '${config.typography.fontWeight.medium}',
      semibold: '${config.typography.fontWeight.semibold}',
      bold: '${config.typography.fontWeight.bold}',
    },
  },

  // Feature Flags
  features: {
    auth: ${config.features.auth},
    socialLogin: {
      google: ${config.features.socialLogin.google},
      apple: ${config.features.socialLogin.apple},
      facebook: ${config.features.socialLogin.facebook},
    },
    biometric: ${config.features.biometric},
    notifications: ${config.features.notifications},
    darkMode: ${config.features.darkMode},
    chat: ${config.features.chat},
    fileUpload: ${config.features.fileUpload},
    offlineMode: ${config.features.offlineMode},
  },

  // Content & Copy
  content: {
    onboarding: {
      step1: {
        title: '${config.content.onboarding.step1.title}',
        description: '${config.content.onboarding.step1.description}',
        icon: '${config.content.onboarding.step1.icon || '👋'}',
      },
      step2: {
        title: '${config.content.onboarding.step2.title}',
        description: '${config.content.onboarding.step2.description}',
        icon: '${config.content.onboarding.step2.icon || '🤝'}',
      },
      step3: {
        title: '${config.content.onboarding.step3.title}',
        description: '${config.content.onboarding.step3.description}',
        icon: '${config.content.onboarding.step3.icon || '🚀'}',
      },
    },
    buttons: {
      primary: '${config.content.buttons.primary}',
      secondary: '${config.content.buttons.secondary}',
      login: '${config.content.buttons.login}',
      signup: '${config.content.buttons.signup}',
    },
    tabs: {
      home: '${config.content.tabs.home}',
      search: '${config.content.tabs.search}',
      notifications: '${config.content.tabs.notifications}',
      profile: '${config.content.tabs.profile}',
    },
  },

  // Navigation
  navigation: {
    tabBar: {
      position: '${config.navigation.tabBar.position}',
      showLabels: ${config.navigation.tabBar.showLabels},
    },
    tabs: ${JSON.stringify(config.navigation.tabs, null, 6).replace(/\n/g, '\n    ')},
  },

  // API Configuration
  apiUrl: '${config.apiUrl}',
  supportEmail: '${config.supportEmail}',

  // Localization
  locale: '${config.locale}',
};
`;
}
